from datetime import date,datetime,timezone
from sqlalchemy import String,Integer,Float,Date,DateTime,Text,UniqueConstraint,ForeignKey,Boolean,Index
from sqlalchemy.orm import Mapped,mapped_column
from app.db.session import Base

def utc_now(): return datetime.now(timezone.utc).replace(tzinfo=None)

class Portfolio(Base):
    __tablename__='portfolios'
    id:Mapped[int]=mapped_column(primary_key=True); user_id:Mapped[int]=mapped_column(ForeignKey('users.id'),index=True); name:Mapped[str]=mapped_column(String(120)); is_default:Mapped[bool]=mapped_column(Boolean,default=False,index=True); created_at:Mapped[datetime]=mapped_column(DateTime,default=utc_now)
    __table_args__=(UniqueConstraint('user_id','name',name='uq_portfolio_user_name'),)
class User(Base):
    __tablename__='users'
    id:Mapped[int]=mapped_column(primary_key=True); email:Mapped[str]=mapped_column(String(320),unique=True,index=True); name:Mapped[str]=mapped_column(String(120)); password_hash:Mapped[str]=mapped_column(String(512)); is_active:Mapped[bool]=mapped_column(Boolean,default=True,index=True); email_verified:Mapped[bool]=mapped_column(Boolean,default=False,index=True); created_at:Mapped[datetime]=mapped_column(DateTime,default=utc_now); updated_at:Mapped[datetime|None]=mapped_column(DateTime,nullable=True)
class AuthSession(Base):
    __tablename__='auth_sessions'
    id:Mapped[int]=mapped_column(primary_key=True); jti:Mapped[str]=mapped_column(String(128),unique=True,index=True); user_id:Mapped[int]=mapped_column(ForeignKey('users.id'),index=True); expires_at:Mapped[datetime]=mapped_column(DateTime); revoked_at:Mapped[datetime|None]=mapped_column(DateTime,nullable=True); created_at:Mapped[datetime]=mapped_column(DateTime,default=utc_now)
class EmailVerificationToken(Base):
    __tablename__='email_verification_tokens'
    id:Mapped[int]=mapped_column(primary_key=True); user_id:Mapped[int]=mapped_column(ForeignKey('users.id'),index=True); token_hash:Mapped[str]=mapped_column(String(128),unique=True,index=True); expires_at:Mapped[datetime]=mapped_column(DateTime); used_at:Mapped[datetime|None]=mapped_column(DateTime,nullable=True); created_at:Mapped[datetime]=mapped_column(DateTime,default=utc_now)
class PasswordResetToken(Base):
    __tablename__='password_reset_tokens'
    id:Mapped[int]=mapped_column(primary_key=True); user_id:Mapped[int]=mapped_column(ForeignKey('users.id'),index=True); token_hash:Mapped[str]=mapped_column(String(128),unique=True,index=True); expires_at:Mapped[datetime]=mapped_column(DateTime); used_at:Mapped[datetime|None]=mapped_column(DateTime,nullable=True); created_at:Mapped[datetime]=mapped_column(DateTime,default=utc_now)
class BrokerConnection(Base):
    __tablename__='broker_connections'
    id:Mapped[int]=mapped_column(primary_key=True); user_id:Mapped[int]=mapped_column(ForeignKey('users.id'),index=True); provider:Mapped[str]=mapped_column(String(32)); access_token_encrypted:Mapped[str]=mapped_column(Text); refresh_token_encrypted:Mapped[str|None]=mapped_column(Text,nullable=True); expires_at:Mapped[datetime|None]=mapped_column(DateTime,nullable=True); connected_at:Mapped[datetime]=mapped_column(DateTime,default=utc_now); updated_at:Mapped[datetime]=mapped_column(DateTime,default=utc_now)
    __table_args__=(UniqueConstraint('user_id','provider',name='uq_broker_user_provider'),)
class ImportJob(Base):
    __tablename__='import_jobs'
    id:Mapped[int]=mapped_column(primary_key=True); user_id:Mapped[int]=mapped_column(ForeignKey('users.id'),index=True); portfolio_id:Mapped[int]=mapped_column(ForeignKey('portfolios.id'),index=True); filename:Mapped[str]=mapped_column(String(255)); status:Mapped[str]=mapped_column(String(32),default='QUEUED',index=True); error:Mapped[str|None]=mapped_column(Text,nullable=True); result_json:Mapped[str|None]=mapped_column(Text,nullable=True); created_at:Mapped[datetime]=mapped_column(DateTime,default=utc_now); started_at:Mapped[datetime|None]=mapped_column(DateTime,nullable=True); completed_at:Mapped[datetime|None]=mapped_column(DateTime,nullable=True)
class ImportBatch(Base):
    __tablename__='import_batches'
    id:Mapped[int]=mapped_column(primary_key=True); user_id:Mapped[int]=mapped_column(ForeignKey('users.id'),index=True); portfolio_id:Mapped[int|None]=mapped_column(ForeignKey('portfolios.id'),index=True,nullable=True); filename:Mapped[str]=mapped_column(String(255)); file_hash:Mapped[str]=mapped_column(String(64)); status:Mapped[str]=mapped_column(String(32),default='PROCESSING'); contract_notes_found:Mapped[int]=mapped_column(Integer,default=0); contracts_added:Mapped[int]=mapped_column(Integer,default=0); duplicates:Mapped[int]=mapped_column(Integer,default=0); executions_added:Mapped[int]=mapped_column(Integer,default=0); security_rows_added:Mapped[int]=mapped_column(Integer,default=0); errors:Mapped[str|None]=mapped_column(Text,nullable=True); source_uri:Mapped[str|None]=mapped_column(Text,nullable=True); created_at:Mapped[datetime]=mapped_column(DateTime,default=utc_now)
    __table_args__=(UniqueConstraint('user_id','file_hash',name='uq_import_user_hash'),)
class ContractNote(Base):
    __tablename__='contract_notes'
    id:Mapped[int]=mapped_column(primary_key=True); user_id:Mapped[int]=mapped_column(ForeignKey('users.id'),index=True); portfolio_id:Mapped[int|None]=mapped_column(ForeignKey('portfolios.id'),index=True,nullable=True); contract_note:Mapped[str]=mapped_column(String(64)); trade_date:Mapped[date]=mapped_column(Date,index=True); settlement_date:Mapped[date|None]=mapped_column(Date,nullable=True); settlement_no:Mapped[str|None]=mapped_column(String(255),nullable=True); source_file:Mapped[str|None]=mapped_column(String(255),nullable=True); contract_note_page:Mapped[int|None]=mapped_column(Integer,nullable=True); annexure_page:Mapped[int|None]=mapped_column(Integer,nullable=True); buy_qty:Mapped[int]=mapped_column(Integer,default=0); sell_qty:Mapped[int]=mapped_column(Integer,default=0); gross_buy_value:Mapped[float]=mapped_column(Float,default=0); gross_sell_value:Mapped[float]=mapped_column(Float,default=0); displayed_brokerage:Mapped[float]=mapped_column(Float,default=0); buy_value_after_brokerage:Mapped[float]=mapped_column(Float,default=0); sell_value_after_brokerage:Mapped[float]=mapped_column(Float,default=0); market_flow_after_brokerage:Mapped[float]=mapped_column(Float,default=0); payin_obligation:Mapped[float]=mapped_column(Float,default=0); taxable_value:Mapped[float]=mapped_column(Float,default=0); stt:Mapped[float]=mapped_column(Float,default=0); cgst:Mapped[float]=mapped_column(Float,default=0); sgst:Mapped[float]=mapped_column(Float,default=0); ugst:Mapped[float]=mapped_column(Float,default=0); igst:Mapped[float]=mapped_column(Float,default=0); exchange_charges:Mapped[float]=mapped_column(Float,default=0); sebi_fees:Mapped[float]=mapped_column(Float,default=0); stamp_duty:Mapped[float]=mapped_column(Float,default=0); ipft:Mapped[float]=mapped_column(Float,default=0); net_amount:Mapped[float]=mapped_column(Float,default=0)
class SecurityLedger(Base):
    __tablename__='security_ledger'
    id:Mapped[int]=mapped_column(primary_key=True); user_id:Mapped[int]=mapped_column(ForeignKey('users.id'),index=True); portfolio_id:Mapped[int|None]=mapped_column(ForeignKey('portfolios.id'),index=True,nullable=True); contract_note:Mapped[str]=mapped_column(String(64)); trade_date:Mapped[date]=mapped_column(Date,index=True); isin:Mapped[str]=mapped_column(String(32),index=True); security:Mapped[str]=mapped_column(String(255),index=True); buy_qty:Mapped[int]=mapped_column(Integer,default=0); buy_wap:Mapped[float]=mapped_column(Float,default=0); buy_brokerage_share:Mapped[float]=mapped_column(Float,default=0); buy_wap_after_brokerage:Mapped[float]=mapped_column(Float,default=0); total_buy_value_after_brokerage:Mapped[float]=mapped_column(Float,default=0); gross_buy:Mapped[float]=mapped_column(Float,default=0); displayed_buy_brokerage:Mapped[float]=mapped_column(Float,default=0); sell_qty:Mapped[int]=mapped_column(Integer,default=0); sell_wap:Mapped[float]=mapped_column(Float,default=0); sell_brokerage_share:Mapped[float]=mapped_column(Float,default=0); sell_wap_after_brokerage:Mapped[float]=mapped_column(Float,default=0); total_sell_value_after_brokerage:Mapped[float]=mapped_column(Float,default=0); gross_sell:Mapped[float]=mapped_column(Float,default=0); displayed_sell_brokerage:Mapped[float]=mapped_column(Float,default=0); net_qty:Mapped[int]=mapped_column(Integer,default=0); net_obligation_before_levies:Mapped[float]=mapped_column(Float,default=0)
class Execution(Base):
    __tablename__='executions'
    id:Mapped[int]=mapped_column(primary_key=True); user_id:Mapped[int]=mapped_column(ForeignKey('users.id'),index=True); portfolio_id:Mapped[int|None]=mapped_column(ForeignKey('portfolios.id'),index=True,nullable=True); contract_note:Mapped[str]=mapped_column(String(64)); trade_date:Mapped[date]=mapped_column(Date,index=True); order_no:Mapped[str]=mapped_column(String(64)); order_time:Mapped[str]=mapped_column(String(32)); trade_no:Mapped[str]=mapped_column(String(64)); trade_time:Mapped[str]=mapped_column(String(32)); security:Mapped[str]=mapped_column(String(255),index=True); exchange:Mapped[str]=mapped_column(String(16)); side:Mapped[str]=mapped_column(String(8)); quantity:Mapped[int]=mapped_column(Integer); market_rate:Mapped[float]=mapped_column(Float); amount:Mapped[float]=mapped_column(Float)
class MarketQuote(Base):
    __tablename__='market_quotes'
    id:Mapped[int]=mapped_column(primary_key=True); user_id:Mapped[int]=mapped_column(ForeignKey('users.id'),index=True); isin:Mapped[str]=mapped_column(String(32),index=True); provider:Mapped[str]=mapped_column(String(32)); symbol:Mapped[str|None]=mapped_column(String(128),nullable=True); ltp:Mapped[float|None]=mapped_column(Float,nullable=True); open:Mapped[float|None]=mapped_column(Float,nullable=True); high:Mapped[float|None]=mapped_column(Float,nullable=True); low:Mapped[float|None]=mapped_column(Float,nullable=True); close:Mapped[float|None]=mapped_column(Float,nullable=True); volume:Mapped[int|None]=mapped_column(Integer,nullable=True); as_of:Mapped[datetime]=mapped_column(DateTime,default=utc_now,index=True)
class InstrumentMapping(Base):
    __tablename__='instrument_mappings'
    id:Mapped[int]=mapped_column(primary_key=True); user_id:Mapped[int]=mapped_column(ForeignKey('users.id'),index=True); isin:Mapped[str]=mapped_column(String(32),index=True); security:Mapped[str]=mapped_column(String(255)); provider:Mapped[str]=mapped_column(String(32)); instrument_key:Mapped[str]=mapped_column(String(128))
class TradeAnnotation(Base):
    __tablename__='trade_annotations'
    id:Mapped[int]=mapped_column(primary_key=True); user_id:Mapped[int]=mapped_column(ForeignKey('users.id'),index=True); security:Mapped[str]=mapped_column(String(255)); buy_date:Mapped[date]=mapped_column(Date); sell_date:Mapped[date]=mapped_column(Date); strategy:Mapped[str]=mapped_column(String(128),default='Unclassified'); setup:Mapped[str]=mapped_column(String(128),default=''); regime:Mapped[str]=mapped_column(String(128),default=''); note:Mapped[str|None]=mapped_column(Text,nullable=True)
