from collections import defaultdict
from statistics import mean, median
from sqlalchemy import select
from sqlalchemy.orm import Session
from app.models.entities import ContractNote, SecurityLedger, Execution
from app.services.analytics import fifo, overview

WORKBOOK_TABS = ['Dashboard','Trader Review','Source of Truth','Dashboard Calc','Contract Notes','Security Ledger','Execution Ledger','Charges Detail','Charge Summary','Charge Allocation','FIFO / Realized P&L','Open Holdings','Realized P&L by Security','Security Summary','Monthly Performance','Cumulative P&L','Reconciliation','Performance Metrics','Source Audit','Data Dictionary','Report Notes','Master Calc']
DATA_DICTIONARY = [
 {'field':'Gross Buy / Sell Value','definition':'Sum of individual exchange execution Amount values for BUY/SELL records.'},
 {'field':'Buy/Sell Value After Brokerage','definition':'Contract-note security table total after brokerage.'},
 {'field':'Displayed Brokerage','definition':'Quantity multiplied by brokerage-per-share shown in the contract note; displayed rates are rounded.'},
 {'field':'Gross Realized P&L','definition':'Gross FIFO sale proceeds less gross FIFO acquisition cost using execution-level amounts.'},
 {'field':'Realized P&L After Brokerage','definition':'FIFO realized P&L using contract-note after-brokerage security totals.'},
 {'field':'Allocated Non-Brokerage Charges','definition':'Analytical allocation of contract-level levies to securities; not a tax computation.'},
 {'field':'Estimated Realized Economic P&L','definition':'Realized P&L after brokerage less allocated non-brokerage charges for fully closed securities.'},
 {'field':'Open Book Cost','definition':'Cost of shares remaining open, after brokerage, based on contract-note totals.'},
 {'field':'Taxable Value of Supply','definition':'Source-reported taxable-value base. It is not an additional charge.'},
 {'field':'Net Amount','definition':'Source-reported final cash amount receivable/payable on each contract note.'},
]

def _month(d): return d.strftime('%Y-%m') if d else None
def _round(v): return round(v,2) if isinstance(v,(int,float)) else v

def build_excel_parity(db: Session):
    o=overview(db); notes=db.scalars(select(ContractNote).order_by(ContractNote.trade_date,ContractNote.id)).all(); secs=db.scalars(select(SecurityLedger).order_by(SecurityLedger.trade_date,SecurityLedger.id)).all(); execs=db.scalars(select(Execution).order_by(Execution.trade_date,Execution.trade_time,Execution.id)).all(); realized,_=fifo(db)
    buy_after_rate={}; sell_after_rate={}
    for s in secs:
        if s.buy_qty: buy_after_rate[(s.security,s.trade_date)]=(-s.total_buy_value_after_brokerage)/s.buy_qty
        if s.sell_qty: sell_after_rate[(s.security,s.trade_date)]=s.total_sell_value_after_brokerage/s.sell_qty
    exec_gross=defaultdict(lambda:{'buy_qty':0,'sell_qty':0,'gross_buy':0.0,'gross_sell':0.0})
    for e in execs:
        z=exec_gross[(e.contract_note,e.security)]
        if e.side=='BUY': z['buy_qty']+=e.quantity; z['gross_buy']+=e.amount
        else: z['sell_qty']+=e.quantity; z['gross_sell']+=e.amount
    trip_tmp=defaultdict(lambda:{'pnl':0.0,'gross':0.0,'cost':0.0,'qty':0})
    for x in realized:
        g=trip_tmp[(x['security'],x['buy_date'],x['sell_date'])]; g['qty']+=x['qty']; g['gross']+=x['pnl']
        br=buy_after_rate.get((x['security'],x['buy_date'])); sr=sell_after_rate.get((x['security'],x['sell_date']))
        if br is not None and sr is not None: g['cost']+=x['qty']*br; g['pnl']+=x['qty']*(sr-br)
        else: g['pnl']+=x['pnl']
    round_trips=[]
    for (security,bd,sd),g in trip_tmp.items(): round_trips.append({'security':security,'buy_date':bd.isoformat(),'sell_date':sd.isoformat(),'qty':g['qty'],'pnl':_round(g['pnl']),'gross_pnl':_round(g['gross']),'return':_round(g['pnl']/g['cost']) if g['cost'] else 0,'holding_days':(sd-bd).days})
    round_trips.sort(key=lambda x:(x['sell_date'],x['buy_date'],x['security']))
    monthly=defaultdict(lambda:{'month':None,'buy_qty':0,'sell_qty':0,'gross_buy_value':0.0,'gross_sell_value':0.0,'buy_executions':0,'sell_executions':0,'net_amount':0.0,'stt':0.0,'cgst':0.0,'sgst':0.0,'ugst':0.0,'igst':0.0,'exchange_charges':0.0,'sebi_fees':0.0,'stamp_duty':0.0,'ipft':0.0,'gross_turnover':0.0,'net_market_flow':0.0,'non_brokerage_charges':0.0,'realized_pnl':0.0,'closed_sell_qty':0,'closed_sell_proceeds':0.0,'closed_fifo_cost':0.0})
    for n in notes:
        m=monthly[_month(n.trade_date)];m['month']=_month(n.trade_date);m['net_amount']+=n.net_amount
        for f in ('stt','cgst','sgst','ugst','igst','exchange_charges','sebi_fees','stamp_duty','ipft'):m[f]+=getattr(n,f)
        m['non_brokerage_charges']+=sum(getattr(n,f) for f in ('stt','cgst','sgst','ugst','igst','exchange_charges','sebi_fees','stamp_duty','ipft'))
    for e in execs:
        m=monthly[_month(e.trade_date)];m['month']=_month(e.trade_date)
        if e.side=='BUY':m['buy_qty']+=e.quantity;m['buy_executions']+=1;m['gross_buy_value']+=e.amount
        else:m['sell_qty']+=e.quantity;m['sell_executions']+=1;m['gross_sell_value']+=e.amount
        m['gross_turnover']+=e.amount
    for x in round_trips:
        m=monthly[x['sell_date'][:7]];m['month']=x['sell_date'][:7];m['realized_pnl']+=x['pnl'];m['closed_sell_qty']+=x['qty']
    for m in monthly.values():m['net_market_flow']=m['gross_sell_value']-m['gross_buy_value']
    monthly_rows=[{k:_round(v) for k,v in m.items()} for _,m in sorted(monthly.items())]
    sec=defaultdict(lambda:{'isin':'','security':'','buy_qty':0,'sell_qty':0,'gross_buy_value':0.0,'gross_sell_value':0.0,'buy_after_brokerage':0.0,'sell_after_brokerage':0.0,'brokerage':0.0})
    for s in secs:
        x=sec[s.isin];x['isin']=s.isin;x['security']=s.security;x['buy_qty']+=s.buy_qty;x['sell_qty']+=s.sell_qty;eg=exec_gross.get((s.contract_note,s.security),{});x['gross_buy_value']+=eg.get('gross_buy',s.gross_buy);x['gross_sell_value']+=eg.get('gross_sell',s.gross_sell);x['buy_after_brokerage']+=-s.total_buy_value_after_brokerage;x['sell_after_brokerage']+=s.total_sell_value_after_brokerage;x['brokerage']+=s.displayed_buy_brokerage+s.displayed_sell_brokerage
    realized_after_by_sec=defaultdict(float);gross_by_sec=defaultdict(float)
    for (security,_,_),g in trip_tmp.items():realized_after_by_sec[security]+=g['pnl'];gross_by_sec[security]+=g['gross']
    sec_rows=[]
    for x in sec.values():
        x['net_qty']=x['buy_qty']-x['sell_qty'];x['turnover']=x['gross_buy_value']+x['gross_sell_value'];closed=x['net_qty']==0;x['gross_pnl']=x['gross_sell_value']-x['gross_buy_value'] if closed else None;x['pnl_after_brokerage']=realized_after_by_sec.get(x['security'],0) if closed else None;x['status']='CLOSED' if closed else 'OPEN';x['avg_book_cost']=x['buy_after_brokerage']/x['buy_qty'] if x['buy_qty'] else None;sec_rows.append({k:_round(v) for k,v in x.items()})
    sec_rows.sort(key=lambda x:(x['status']!='OPEN',-(x['pnl_after_brokerage'] or x['buy_after_brokerage'] or 0)))
    daily=o['daily_pnl']; cumulative=[];run=peak=0.0
    for x in daily:run+=x['pnl'];peak=max(peak,run);cumulative.append({'date':x['date'],'daily_pnl':_round(x['pnl']),'cumulative_pnl':_round(run),'drawdown':_round(run-peak)})
    charge_rows=[]
    for label,value in [('Brokerage (displayed)',o['brokerage']),('STT',sum(n.stt for n in notes)),('CGST',sum(n.cgst for n in notes)),('SGST',sum(n.sgst for n in notes)),('UGST',sum(n.ugst for n in notes)),('IGST',sum(n.igst for n in notes)),('Exchange Transaction Charges',sum(n.exchange_charges for n in notes)),('SEBI Turnover Fees',sum(n.sebi_fees for n in notes)),('Stamp Duty',sum(n.stamp_duty for n in notes)),('IPFT Charges',sum(n.ipft for n in notes))]:charge_rows.append({'charge_type':label,'amount':_round(value),'pct_turnover':_round(value/o['gross_turnover']) if o['gross_turnover'] else 0})
    allocation_rows=[];allocated_by_sec=defaultdict(float);closed_alloc=0.0
    for n in notes:
        ns=[s for s in secs if s.contract_note==n.contract_note];total=sum(exec_gross.get((s.contract_note,s.security),{}).get('gross_buy',s.gross_buy)+exec_gross.get((s.contract_note,s.security),{}).get('gross_sell',s.gross_sell) for s in ns);buy_total=sum(exec_gross.get((s.contract_note,s.security),{}).get('gross_buy',s.gross_buy) for s in ns);lev=sum(getattr(n,f) for f in ('stt','cgst','sgst','ugst','igst','exchange_charges','sebi_fees','ipft'))
        for s in ns:
            eg=exec_gross.get((s.contract_note,s.security),{});gb=eg.get('gross_buy',s.gross_buy);gs=eg.get('gross_sell',s.gross_sell);base=gb+gs;allocated=lev*(base/total if total else 0)+n.stamp_duty*(gb/buy_total if buy_total else 0);allocated_by_sec[s.isin]+=allocated;allocation_rows.append({'contract_note':n.contract_note,'security':s.security,'isin':s.isin,'buy_qty':s.buy_qty,'sell_qty':s.sell_qty,'gross_buy':_round(gb),'gross_sell':_round(gs),'gross_turnover':_round(base),'brokerage_base':_round(s.displayed_buy_brokerage+s.displayed_sell_brokerage),'allocated_non_brokerage_charges':_round(allocated)})
    realized_security_rows=[];realized_economic=0.0
    for x in sec_rows:
        if x['status']!='CLOSED':continue
        alloc=allocated_by_sec.get(x['isin'],0);closed_alloc+=alloc;econ=(x['pnl_after_brokerage'] or 0)-alloc;realized_economic+=econ;realized_security_rows.append({'isin':x['isin'],'security':x['security'],'qty_sold':x['sell_qty'],'proceeds_after_brokerage':x['sell_after_brokerage'],'fifo_cost':x['buy_after_brokerage'],'realized_pnl':x['pnl_after_brokerage'],'return':(x['pnl_after_brokerage']/x['buy_after_brokerage']) if x['buy_after_brokerage'] else 0,'gross_proceeds':x['gross_sell_value'],'gross_cost':x['gross_buy_value'],'gross_realized_pnl':x['gross_pnl'],'brokerage_execution_drag':(x['gross_pnl'] or 0)-(x['pnl_after_brokerage'] or 0),'allocated_non_brokerage_charges':_round(alloc),'estimated_realized_economic_pnl':_round(econ)})
    wins=sum(x['pnl']>0 for x in round_trips);losses=len(round_trips)-wins;vals=[x['pnl'] for x in round_trips];avg_win=mean([x['pnl'] for x in round_trips if x['pnl']>0]) if wins else None;avg_loss=mean([x['pnl'] for x in round_trips if x['pnl']<=0]) if losses else None;profit_factor=sum(x['pnl'] for x in round_trips if x['pnl']>0)/abs(sum(x['pnl'] for x in round_trips if x['pnl']<0)) if any(x['pnl']<0 for x in round_trips) else None
    metrics={'contract_notes':o['contracts'],'execution_records':o['executions'],'unique_securities':o['unique_securities'],'buy_qty':o['buy_qty'],'sell_qty':o['sell_qty'],'open_qty':o['open_qty'],'gross_turnover':_round(o['gross_turnover']),'gross_realized_pnl':_round(o['gross_realized_pnl']),'realized_pnl_after_brokerage':_round(o['realized_pnl']),'estimated_realized_economic_pnl':_round(realized_economic),'displayed_brokerage':_round(o['brokerage']),'non_brokerage_levies':_round(o['non_brokerage_charges']),'open_book_cost':_round(o['open_book_cost']),'total_actual_charges':_round(o['total_charges']),'actual_net_cash_amount':_round(sum(n.net_amount for n in notes)),'win_rate':_round(wins/len(round_trips)) if round_trips else None,'wins':wins,'losses':losses,'average_round_trip_pnl':_round(mean(vals)) if vals else None,'median_round_trip_pnl':_round(median(vals)) if vals else None,'expectancy_per_round_trip':_round(mean(vals)) if vals else None,'avg_win':_round(avg_win) if avg_win is not None else None,'avg_loss':_round(avg_loss) if avg_loss is not None else None,'payoff_ratio':_round(avg_win/abs(avg_loss)) if avg_win is not None and avg_loss else None,'profit_factor':_round(profit_factor) if profit_factor is not None else None,'realized_to_turnover':_round(o['realized_pnl']/o['gross_turnover']) if o['gross_turnover'] else 0,'brokerage_drag_pct':_round((o['gross_realized_pnl']-o['realized_pnl'])/o['gross_realized_pnl']) if o['gross_realized_pnl'] else 0,'top2_concentration':_round(o['top2_concentration']),'top3_concentration':_round(o['top3_concentration']),'avg_holding_days':_round(o['avg_holding_days']) if o['avg_holding_days'] is not None else None}
    contract_rows=[];security_counts=defaultdict(int);note_exec=defaultdict(lambda:{'buy_qty':0,'sell_qty':0,'gross_buy':0.0,'gross_sell':0.0})
    for s in secs:security_counts[s.contract_note]+=1
    for e in execs:
        z=note_exec[e.contract_note];z['buy_qty']+=e.quantity if e.side=='BUY' else 0;z['sell_qty']+=e.quantity if e.side=='SELL' else 0;z['gross_buy']+=e.amount if e.side=='BUY' else 0;z['gross_sell']+=e.amount if e.side=='SELL' else 0
    for n in notes:
        z=note_exec[n.contract_note];lev=sum(getattr(n,f) for f in ('stt','cgst','sgst','ugst','igst','exchange_charges','sebi_fees','stamp_duty','ipft'));contract_rows.append({'contract_note':n.contract_note,'trade_date':n.trade_date.isoformat(),'settlement_no':n.settlement_no,'settlement_date':n.settlement_date.isoformat() if n.settlement_date else None,'contract_note_page':n.contract_note_page,'annexure_page':n.annexure_page,'securities':security_counts[n.contract_note],'buy_qty':z['buy_qty'] or n.buy_qty,'sell_qty':z['sell_qty'] or n.sell_qty,'gross_buy_value':_round(z['gross_buy'] or n.gross_buy_value),'gross_sell_value':_round(z['gross_sell'] or n.gross_sell_value),'gross_turnover':_round(z['gross_buy']+z['gross_sell']),'displayed_brokerage':_round(n.displayed_brokerage),'buy_value_after_brokerage':_round(n.buy_value_after_brokerage),'sell_value_after_brokerage':_round(n.sell_value_after_brokerage),'market_flow_after_brokerage':_round(n.market_flow_after_brokerage),'payin_obligation':_round(n.payin_obligation),'taxable_value':_round(n.taxable_value),'stt':_round(n.stt),'cgst':_round(n.cgst),'sgst':_round(n.sgst),'ugst':_round(n.ugst),'igst':_round(n.igst),'exchange_charges':_round(n.exchange_charges),'sebi_fees':_round(n.sebi_fees),'stamp_duty':_round(n.stamp_duty),'ipft':_round(n.ipft),'non_brokerage_charges':_round(lev),'net_amount':_round(n.net_amount)})
    execution_rows=[{'trade_date':e.trade_date.isoformat(),'contract_note':e.contract_note,'order_no':e.order_no,'order_time':e.order_time,'trade_no':e.trade_no,'trade_time':e.trade_time,'security':e.security,'exchange':e.exchange,'side':e.side,'quantity':e.quantity,'market_rate':_round(e.market_rate),'amount':_round(e.amount)} for e in execs]
    gross_buy=sum(e.amount for e in execs if e.side=='BUY');gross_sell=sum(e.amount for e in execs if e.side=='SELL');buy_after=sum(-s.total_buy_value_after_brokerage for s in secs);sell_after=sum(s.total_sell_value_after_brokerage for s in secs);source_net=sum(n.net_amount for n in notes);levies=sum(n.stt+n.cgst+n.sgst+n.ugst+n.igst+n.exchange_charges+n.sebi_fees+n.stamp_duty+n.ipft for n in notes)
    reconciliation=[{'item':'Gross buy value from exchange executions','amount':_round(gross_buy)},{'item':'Gross sell value from exchange executions','amount':_round(gross_sell)},{'item':'Gross market cash flow','amount':_round(gross_sell-gross_buy)},{'item':'Contract-note buy value after brokerage','amount':_round(buy_after)},{'item':'Contract-note sell value after brokerage','amount':_round(sell_after)},{'item':'Net market flow after brokerage','amount':_round(sell_after-buy_after)},{'item':'Total actual charges','amount':_round(o['total_charges'])},{'item':'Source net amount','amount':_round(source_net)},{'item':'Cash reconciliation variance','amount':_round(source_net-((sell_after-buy_after)-levies))},{'item':'Gross realized P&L (closed positions)','amount':_round(o['gross_realized_pnl'])},{'item':'Realized P&L after brokerage','amount':_round(o['realized_pnl'])},{'item':'Allocated non-brokerage charges on closed securities','amount':_round(closed_alloc)},{'item':'Estimated realized economic P&L after allocated levies','amount':_round(realized_economic)}]
    performance_metrics=[{'metric':k,'value':v} for k,v in metrics.items()];source_audit=[{'contract_note':n.contract_note,'trade_date':n.trade_date.isoformat(),'settlement_no':n.settlement_no,'settlement_date':n.settlement_date.isoformat() if n.settlement_date else None,'contract_note_page':n.contract_note_page,'annexure_page':n.annexure_page,'buy_qty':n.buy_qty,'sell_qty':n.sell_qty,'execution_qty':sum(e.quantity for e in execs if e.contract_note==n.contract_note),'net_amount':_round(n.net_amount)} for n in notes]
    return {'workbook_tabs':WORKBOOK_TABS,'dashboard':{'title':'JM FINANCIAL — MASTER TRADER PERFORMANCE DASHBOARD','source_scope':'99-page contract-note bundle • 33 contract notes • 92 executions • 14 securities','metrics':metrics,'top_closed':sorted(realized_security_rows,key=lambda x:x['realized_pnl'] or 0,reverse=True)[:8],'top_open':o['holdings'][:6],'round_trips':round_trips,'monthly':monthly_rows,'alerts':['Top 3 open positions exceed 90% of open book cost.'] if o['top3_concentration']>.90 else []},'trader_review':{'executive_conclusion':f"Closed-trade performance is {'strong' if metrics['realized_pnl_after_brokerage']>0 else 'negative'}: ₹{metrics['realized_pnl_after_brokerage']:,.2f} realized P&L after brokerage across {len(round_trips)} FIFO round trips, {wins} winners and {losses} losers.",'priority_flags':[{'priority':1,'area':'Capital concentration','finding':f"Top 3 open positions represent {o['top3_concentration']*100:.1f}% of open book cost."},{'priority':2,'area':'Cost efficiency','finding':f"All-in charges are {(o['total_charges']/o['gross_turnover']*10000) if o['gross_turnover'] else 0:.1f} bps of gross turnover."}]},'source_of_truth':{'contract_notes':o['contracts'],'executions':o['executions'],'unique_securities':o['unique_securities'],'gross_turnover':_round(o['gross_turnover']),'realized_pnl_after_brokerage':_round(o['realized_pnl']),'total_actual_charges':_round(o['total_charges']),'open_book_cost':_round(o['open_book_cost']),'cash_reconciliation_variance':reconciliation[8]['amount']},'dashboard_calc':[{'month':m['month'],'buy_value':m['gross_buy_value'],'sell_value':m['gross_sell_value'],'gross_turnover':m['gross_turnover'],'net_market_flow':m['net_market_flow'],'buy_qty':m['buy_qty'],'sell_qty':m['sell_qty'],'non_brokerage_charges':m['non_brokerage_charges'],'realized_pnl':m['realized_pnl']} for m in monthly_rows],'metrics':metrics,'monthly':monthly_rows,'securities':sec_rows,'realized_by_security':realized_security_rows,'holdings':o['holdings'],'cumulative_pnl':cumulative,'charges':charge_rows,'charge_allocation':allocation_rows,'round_trips':round_trips,'contract_notes':contract_rows,'executions':execution_rows,'reconciliation':reconciliation,'performance_metrics':performance_metrics,'source_audit':source_audit,'data_dictionary':DATA_DICTIONARY,'report_notes':[{'topic':'Source scope','note':'99-page JM Financial Services contract-note PDF supplied for analysis.'},{'topic':'P&L method','note':'FIFO is used for realized P&L; after-brokerage economics use contract-note security totals.'},{'topic':'Charges','note':'All source-reported levies are preserved separately from taxable-value bases.'},{'topic':'Economic P&L','note':'Allocated levies are analytical, not a tax computation.'},{'topic':'Current valuation','note':'Current market prices are supplied only by the configured live market-data layer.'}],'master_calc':cumulative}
