import {useEffect,useState} from 'react';
import {auth,get,logout} from './lib/api';
import Dashboard from './pages/Dashboard'; import ExcelParity from './pages/ExcelParity'; import Imports from './pages/Imports'; import Data from './pages/Data'; import Intelligence from './pages/Intelligence'; import Mappings from './pages/Mappings'; import Advanced from './pages/Advanced'; import Login from './pages/Login'; import Register from './pages/Register';
const items:any[]=[['dashboard','Dashboard',Dashboard],['parity','Excel Parity',ExcelParity],['imports','Imports',Imports],['realized','Realized P&L',()=> <Data title="Realized P&L" endpoint="/realized" exportKey="realized"/>],['holdings','Open Holdings',()=> <Data title="Open Holdings" endpoint="/holdings" exportKey="holdings"/>],['contracts','Contract Notes',()=> <Data title="Contract Notes" endpoint="/tables/contracts" exportKey="contracts"/>],['executions','Execution Ledger',()=> <Data title="Execution Ledger" endpoint="/tables/executions" exportKey="executions"/>],['securities','Security Ledger',()=> <Data title="Security Ledger" endpoint="/securities" exportKey="securities"/>],['charges','Charges',()=> <Data title="Charges" endpoint="/charges" exportKey="charges"/>],['missing','Missing Dates',()=> <Data title="Missing Dates" endpoint="/missing-dates" exportKey="missing-dates"/>],['market','Live Market Data',Mappings],['risk','Risk & Intelligence',Intelligence],['advanced','Advanced Analytics',Advanced]];
export default function App(){
 const [user,setUser]=useState<any>(null); const [loading,setLoading]=useState(true); const [screen,setScreen]=useState<'login'|'register'>('login'); const [tab,setTab]=useState('dashboard'); const [portfolios,setPortfolios]=useState<any[]>([]); const [portfolioId,setPortfolioId]=useState<number|null>(auth.portfolioId);
 useEffect(()=>{const onExpired=()=>{setUser(null);setScreen('login')};window.addEventListener('auth-expired',onExpired); if(auth.access){Promise.all([get('/auth/me'),get('/portfolios')]).then(([u,p])=>{setUser(u);setPortfolios(p); if(!auth.portfolioId&&p[0]){auth.setPortfolio(p[0].id);setPortfolioId(p[0].id)}}).catch(()=>{auth.clear();setUser(null)}).finally(()=>setLoading(false))}else setLoading(false);return()=>window.removeEventListener('auth-expired',onExpired)},[]);
 const onAuth=(data:any)=>{if(data?.showRegister){setScreen('register');return} if(data?.showLogin){setScreen('login');return} const nextUser=data?.user||data; setUser(nextUser);get('/portfolios').then((p:any[])=>{setPortfolios(p);if(p[0]&&!auth.portfolioId){auth.setPortfolio(p[0].id);setPortfolioId(p[0].id)}else setPortfolioId(auth.portfolioId)}).catch(()=>{})};
 if(loading)return <div className="auth-shell"><div className="auth-card"><div className="eyebrow">JM TRADING INTELLIGENCE</div><h1>Loading session…</h1></div></div>;
 if(!user)return screen==='login'?<Login onAuthenticated={onAuth} onCreateAccount={()=>setScreen('register')}/>:<Register onAuthenticated={onAuth}/>;
 const found=items.find(x=>x[0]===tab)||items[0]; const Component:any=found[2];
 return <div className="app"><aside><div className="brand">JM Trading<br/>Intelligence</div><div className="userbox"><strong>{user.name}</strong><span>{user.email}</span></div><div className="portfolio-select"><label>Portfolio<select value={portfolioId??''} onChange={e=>{const id=Number(e.target.value);auth.setPortfolio(id);setPortfolioId(id)}}>{portfolios.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label></div><nav>{items.map(([id,label]:any)=><button className={tab===id?'active':''} key={id} onClick={()=>setTab(String(id))}>{String(label)}</button>)}</nav><div className="sidebar-foot"><button className="logout" onClick={async()=>{await logout();setUser(null)}}>Sign out</button><div>Private account · JWT auth</div><div>Deterministic FIFO · Live Market Layer</div><div>Multiple portfolios · paginated data</div></div></aside><main><Component key={`${tab}-${portfolioId}`}/></main></div>
}
