export const API=import.meta.env.VITE_API_URL||'/api';
const ACCESS_KEY='jmti_access_token'; const PORTFOLIO_KEY='jmti_portfolio_id';
export type SessionUser={id:number,email:string,name:string,email_verified?:boolean};
export const auth={get access(){return localStorage.getItem(ACCESS_KEY)},get portfolioId(){const raw=localStorage.getItem(PORTFOLIO_KEY);return raw?Number(raw):null},save(data:any){if(data.access_token)localStorage.setItem(ACCESS_KEY,data.access_token);if(data.portfolio?.id)localStorage.setItem(PORTFOLIO_KEY,String(data.portfolio.id));},setPortfolio(id:number){localStorage.setItem(PORTFOLIO_KEY,String(id))},clear(){localStorage.removeItem(ACCESS_KEY);localStorage.removeItem(PORTFOLIO_KEY)}};
function scoped(path:string){if(!auth.portfolioId||path.startsWith('/auth/')||path==='/portfolios'||path.startsWith('/portfolios/'))return path;const prefixes=['/dashboard','/intelligence','/analytics/','/risk','/performance/','/holdings','/realized','/missing-dates','/tables/','/charges','/securities','/excel-parity','/imports','/trade-annotations','/quotes/refresh','/export/'];if(!prefixes.some(p=>path.startsWith(p)))return path;const join=path.includes('?')?'&':'?';return path.includes('portfolio_id=')?path:`${path}${join}portfolio_id=${encodeURIComponent(String(auth.portfolioId))}`}
async function refreshSession(){const r=await fetch(API+'/auth/refresh',{method:'POST',credentials:'include'});if(!r.ok){auth.clear();return false}auth.save(await r.json());return true}
async function request(path:string,init:RequestInit={},retry=true){const finalPath=scoped(path);const headers=new Headers(init.headers||{});const token=auth.access;if(token)headers.set('Authorization',`Bearer ${token}`);const r=await fetch(API+finalPath,{...init,headers,credentials:'include'});if(r.status===401&&retry&&!finalPath.startsWith('/auth/')){if(await refreshSession())return request(path,init,false);auth.clear();window.dispatchEvent(new Event('auth-expired'))}if(!r.ok){let detail='Request failed';try{const body=await r.json();detail=body.detail||JSON.stringify(body)}catch{detail=await r.text()||detail}throw new Error(detail)}return r.status===204?null:r.json()}
export async function get<T=any>(path:string):Promise<T>{return request(path)}
export async function post<T=any>(path:string,body:any):Promise<T>{return request(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})}
export async function patch<T=any>(path:string,body:any):Promise<T>{return request(path,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})}
export async function upload(files:File[],background=false){const f=new FormData();files.forEach(x=>f.append('files',x));return request(background?'/imports/upload/background':'/imports/upload',{method:'POST',body:f})}
export async function downloadDataset(key:string){return request(`/export/${key}`)}
export async function login(email:string,password:string){const r=await request('/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})},false);auth.save(r);return r}
export async function register(name:string,email:string,password:string){const r=await request('/auth/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,email,password})},false);auth.save(r);return r}
export async function logout(){await request('/auth/logout',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({})},false).catch(()=>{});auth.clear()}
